% Limits
ClusterLimits.StartTime = [0, 20];          % ns
ClusterLimits.IntervalTime = [1, 10];       % ns
ClusterLimits.StartPower = [0.01, 1];       % V
ClusterLimits.DecayPower = [0.9, 8];       % 
ClusterLimits.Number = [2, 8];              % 

rnd = @(a) a(1) + (a(2)-a(1)).*rand(1,1);
rndi = @(a) a(1) + randi((a(2)-a(1)),1,1);

lb = [...
	ClusterLimits.StartTime(1),...
	ClusterLimits.IntervalTime(1),...
	ClusterLimits.StartPower(1),...
	ClusterLimits.DecayPower(1),...
	ClusterLimits.Number(1),...
	ClusterLimits.StartTime(1),...
	ClusterLimits.IntervalTime(1),...
	ClusterLimits.StartPower(1),...
	ClusterLimits.DecayPower(1),...
	ClusterLimits.Number(1),...
	ClusterLimits.StartTime(1),...
	ClusterLimits.IntervalTime(1),...
	ClusterLimits.StartPower(1),...
	ClusterLimits.DecayPower(1),...
	ClusterLimits.Number(1),...
	ClusterLimits.StartTime(1),...
	ClusterLimits.IntervalTime(1),...
	ClusterLimits.StartPower(1),...
	ClusterLimits.DecayPower(1),...
	ClusterLimits.Number(1)];

ub = [...
	ClusterLimits.StartTime(2),...
	ClusterLimits.IntervalTime(2),...
	ClusterLimits.StartPower(2),...
	ClusterLimits.DecayPower(2),...
	ClusterLimits.Number(2),...
	ClusterLimits.StartTime(2),...
	ClusterLimits.IntervalTime(2),...
	ClusterLimits.StartPower(2),...
	ClusterLimits.DecayPower(2),...
	ClusterLimits.Number(2),...
	ClusterLimits.StartTime(2),...
	ClusterLimits.IntervalTime(2),...
	ClusterLimits.StartPower(2),...
	ClusterLimits.DecayPower(2),...
	ClusterLimits.Number(2),...
	ClusterLimits.StartTime(2),...
	ClusterLimits.IntervalTime(2),...
	ClusterLimits.StartPower(2),...
	ClusterLimits.DecayPower(2),...
	ClusterLimits.Number(2)];

args(1)  = rnd(ClusterLimits.StartTime);   
args(2)  = rnd(ClusterLimits.IntervalTime);
args(3)  = rnd(ClusterLimits.StartPower);  
args(4)  = rnd(ClusterLimits.DecayPower);  
args(5)  = rndi(ClusterLimits.Number);     
args(6)  = rnd(ClusterLimits.StartTime);   
args(7)  = rnd(ClusterLimits.IntervalTime);
args(8)  = rnd(ClusterLimits.StartPower);  
args(9)  = rnd(ClusterLimits.DecayPower);  
args(10) = rndi(ClusterLimits.Number);     
args(11) = rnd(ClusterLimits.StartTime);   
args(12) = rnd(ClusterLimits.IntervalTime);
args(13) = rnd(ClusterLimits.StartPower);  
args(14) = rnd(ClusterLimits.DecayPower);  
args(15) = rndi(ClusterLimits.Number);     
args(16) = rnd(ClusterLimits.StartTime);   
args(17) = rnd(ClusterLimits.IntervalTime);
args(18) = rnd(ClusterLimits.StartPower);  
args(19) = rnd(ClusterLimits.DecayPower);  
args(20) = rndi(ClusterLimits.Number);     

options = optimset('TolFun', 60, 'MaxFunEvals', 1000);
[x, f] = fmincon(@CostStraigntCompare, args, [], [], [], [], lb, ub, [], options);

[fit, y1, y2, x] = CostStraigntCompare( x );
semilogy(x, y1, x, y2);

